#   A basic travis.yml boilerplate for Django projects
#
#   The set-up assumes a postgreSQL database.
#
#   Replace the following variables in the code:
# * your_project_settings
# * your_github_username
# * your_repo

language: python

python:
  - 3.6

services: postgresql

env:
  - DJANGO=2.0.3

# before_install:
#   - export DJANGO_SETTINGS_MODULE=your_project.settings
#   - export PYTHONPATH=$HOME/builds/your_github_username/your_repo
#   - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  # - pip install django==$DJANGO --quiet
  # - pip install psycopg2 --quiet
  - pip install coveralls radon

# before_script:
#   - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  # - python manage.py syncdb --noinput
  - python manage.py migrate
  - python manage.py test

after_success:
  - pip freeze
  - echo Uploading code coverage data ...; coveralls
  - echo Code complexity scores:; radon cc --min B ../pony-forum
  